path: '/home/suyanne/Documents/edra/cbr_base_detector' # dataset root dir
train: images # train images (relative to 'path')
val: images  # val images (relative to 'path')

# Classes
names:
  0: cbr_base
